package content

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"
)

// PatternSynthesisThreshold — number of new journal entries after the last
// synthesis at which the periodic worker will re-run pattern extraction.
// Chosen small enough to catch behaviour drift, large enough that a single
// bad entry doesn't distort the summary.
const PatternSynthesisThreshold = 5

// PersonaPatterns holds the compressed synthesis of a persona's journal —
// 3-5 durable patterns generated by Sonnet from the raw entries. Replaces
// itself on each synthesis pass rather than growing append-only.
type PersonaPatterns struct {
	SynthesisedAt      time.Time `json:"synthesised_at"`
	EntriesAtSynthesis int       `json:"entries_at_synthesis"`
	Patterns           string    `json:"patterns"`
	Model              string    `json:"model,omitempty"`
}

// PersonaJournalEntry is one reflection a persona wrote after a ritual where
// their recommendation turned out wrong (rollback / fix commit within the
// tracking window). Journals only capture mistakes — success needs no
// self-correction.
type PersonaJournalEntry struct {
	At             time.Time `json:"at"`
	NaradaID       string    `json:"narada_id"`
	Context        string    `json:"context"`
	Recommendation string    `json:"recommendation"`
	ErrorSignal    string    `json:"error_signal"`
	Reflection     string    `json:"reflection"`
}

// PersonaJournalStore keeps one markdown file per persona slug under
// /data/persona-journals/. Append-only. A rewrite is only allowed as part of
// a full rewrite (test cleanup or admin ops).
type PersonaJournalStore struct {
	dir string
	mu  sync.Mutex
}

func NewPersonaJournalStore(contentDir string) *PersonaJournalStore {
	dataDir := filepath.Dir(contentDir)
	dir := filepath.Join(dataDir, "persona-journals")
	_ = os.MkdirAll(dir, 0o755)
	return &PersonaJournalStore{dir: dir}
}

// Append writes one entry to the persona's journal. Concurrent-safe.
// Rejects entries with empty slug, narada_id, or reflection — those three
// are the minimum useful record.
func (s *PersonaJournalStore) Append(slug string, e PersonaJournalEntry) error {
	slug = strings.TrimSpace(strings.ToLower(slug))
	if slug == "" {
		return fmt.Errorf("persona slug required")
	}
	if !isSafeSlug(slug) {
		return fmt.Errorf("invalid persona slug")
	}
	if strings.TrimSpace(e.NaradaID) == "" {
		return fmt.Errorf("narada_id required")
	}
	if strings.TrimSpace(e.Reflection) == "" {
		return fmt.Errorf("reflection required")
	}
	if e.At.IsZero() {
		e.At = time.Now().UTC()
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	path := s.pathFor(slug)
	existing, _ := os.ReadFile(path)

	var buf strings.Builder
	if len(existing) == 0 {
		fmt.Fprintf(&buf, "# Dziennik persony: %s\n\n", slug)
		buf.WriteString("_Wpisy dopisywane po naradach, w których rekomendacja tej persony została odwrócona (rollback / poprawka)._\n\n")
	} else {
		buf.Write(existing)
		if !strings.HasSuffix(string(existing), "\n") {
			buf.WriteString("\n")
		}
		buf.WriteString("\n")
	}
	renderEntry(&buf, e)
	return os.WriteFile(path, []byte(buf.String()), 0o644)
}

// List returns all entries for a persona, newest-first. Empty slice when
// the persona has no journal yet.
func (s *PersonaJournalStore) List(slug string) ([]PersonaJournalEntry, error) {
	slug = strings.TrimSpace(strings.ToLower(slug))
	if !isSafeSlug(slug) {
		return nil, fmt.Errorf("invalid persona slug")
	}
	s.mu.Lock()
	defer s.mu.Unlock()

	data, err := os.ReadFile(s.pathFor(slug))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	entries := parseJournal(string(data))
	sort.Slice(entries, func(i, j int) bool { return entries[i].At.After(entries[j].At) })
	return entries, nil
}

// Render returns the raw markdown content for a persona's journal, or the
// empty string when there is no journal yet. Owner-facing display uses this.
func (s *PersonaJournalStore) Render(slug string) (string, error) {
	slug = strings.TrimSpace(strings.ToLower(slug))
	if !isSafeSlug(slug) {
		return "", fmt.Errorf("invalid persona slug")
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	data, err := os.ReadFile(s.pathFor(slug))
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	return string(data), nil
}

func (s *PersonaJournalStore) pathFor(slug string) string {
	return filepath.Join(s.dir, slug+".md")
}

func (s *PersonaJournalStore) patternsPath(slug string) string {
	return filepath.Join(s.dir, slug+"-patterns.json")
}

// WritePatterns replaces the persona's compressed pattern set. Every
// synthesis overwrites the previous file — patterns are a living document,
// not an append-only log (the raw journal already fills that role).
func (s *PersonaJournalStore) WritePatterns(slug string, p PersonaPatterns) error {
	slug = strings.TrimSpace(strings.ToLower(slug))
	if !isSafeSlug(slug) {
		return fmt.Errorf("invalid persona slug")
	}
	if strings.TrimSpace(p.Patterns) == "" {
		return fmt.Errorf("patterns body required")
	}
	if p.SynthesisedAt.IsZero() {
		p.SynthesisedAt = time.Now().UTC()
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	data, err := json.MarshalIndent(p, "", "  ")
	if err != nil {
		return err
	}
	tmp := s.patternsPath(slug) + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, s.patternsPath(slug))
}

// ReadPatterns returns the current pattern set for a persona. Returns a
// zero-value PersonaPatterns (not an error) when the file is missing —
// callers treat "no patterns yet" as a normal state, not a failure.
func (s *PersonaJournalStore) ReadPatterns(slug string) (PersonaPatterns, error) {
	slug = strings.TrimSpace(strings.ToLower(slug))
	if !isSafeSlug(slug) {
		return PersonaPatterns{}, fmt.Errorf("invalid persona slug")
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	data, err := os.ReadFile(s.patternsPath(slug))
	if err != nil {
		if os.IsNotExist(err) {
			return PersonaPatterns{}, nil
		}
		return PersonaPatterns{}, err
	}
	var p PersonaPatterns
	if err := json.Unmarshal(data, &p); err != nil {
		return PersonaPatterns{}, err
	}
	return p, nil
}

// NeedsSynthesis reports true when the persona has at least
// PatternSynthesisThreshold new journal entries since the last synthesis.
// A persona with no patterns yet needs synthesis once it has any journal
// entries (>= threshold). The periodic worker uses this to decide who to
// process on each tick.
func (s *PersonaJournalStore) NeedsSynthesis(slug string) (bool, int, error) {
	entries, err := s.List(slug)
	if err != nil {
		return false, 0, err
	}
	total := len(entries)
	if total == 0 {
		return false, 0, nil
	}
	pat, err := s.ReadPatterns(slug)
	if err != nil {
		return false, total, err
	}
	newEntries := total - pat.EntriesAtSynthesis
	return newEntries >= PatternSynthesisThreshold, newEntries, nil
}

// ListSlugsWithJournal returns every persona slug that has at least one
// journal file on disk. Used by the synthesis worker to iterate candidates.
func (s *PersonaJournalStore) ListSlugsWithJournal() ([]string, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	entries, err := os.ReadDir(s.dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var slugs []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		// Skip the patterns sidecars — we want journal .md files only.
		if !strings.HasSuffix(name, ".md") || strings.HasSuffix(name, "-patterns.md") {
			continue
		}
		slugs = append(slugs, strings.TrimSuffix(name, ".md"))
	}
	sort.Strings(slugs)
	return slugs, nil
}

// isSafeSlug allows only [a-z0-9-] to keep path traversal impossible.
func isSafeSlug(slug string) bool {
	if slug == "" {
		return false
	}
	for _, r := range slug {
		switch {
		case r >= 'a' && r <= 'z':
		case r >= '0' && r <= '9':
		case r == '-':
		default:
			return false
		}
	}
	return true
}

func renderEntry(buf *strings.Builder, e PersonaJournalEntry) {
	fmt.Fprintf(buf, "## %s · %s\n\n", e.At.Format("2006-01-02 15:04 UTC"), e.NaradaID)
	if s := strings.TrimSpace(e.Context); s != "" {
		fmt.Fprintf(buf, "**Kontekst:** %s\n\n", s)
	}
	if s := strings.TrimSpace(e.Recommendation); s != "" {
		fmt.Fprintf(buf, "**Rekomendacja:** %s\n\n", s)
	}
	if s := strings.TrimSpace(e.ErrorSignal); s != "" {
		fmt.Fprintf(buf, "**Sygnał błędu:** %s\n\n", s)
	}
	buf.WriteString("**Wniosek:**\n\n")
	for _, line := range strings.Split(strings.TrimSpace(e.Reflection), "\n") {
		fmt.Fprintf(buf, "> %s\n", line)
	}
	buf.WriteString("\n")
}

var entryHeaderRE = regexp.MustCompile(`(?m)^## (\S+ \S+ \S+) · (\S+)\s*$`)

func parseJournal(raw string) []PersonaJournalEntry {
	locs := entryHeaderRE.FindAllStringSubmatchIndex(raw, -1)
	if len(locs) == 0 {
		return nil
	}
	var out []PersonaJournalEntry
	for i, loc := range locs {
		start := loc[0]
		end := len(raw)
		if i+1 < len(locs) {
			end = locs[i+1][0]
		}
		block := raw[start:end]
		e := parseEntry(block)
		if e.NaradaID != "" {
			out = append(out, e)
		}
	}
	return out
}

func parseEntry(block string) PersonaJournalEntry {
	e := PersonaJournalEntry{}
	m := entryHeaderRE.FindStringSubmatch(block)
	if len(m) < 3 {
		return e
	}
	e.At, _ = time.Parse("2006-01-02 15:04 UTC", m[1])
	e.NaradaID = m[2]

	var reflection []string
	inReflection := false
	for _, line := range strings.Split(block, "\n") {
		trimmed := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(trimmed, "**Kontekst:**"):
			e.Context = strings.TrimSpace(strings.TrimPrefix(trimmed, "**Kontekst:**"))
			inReflection = false
		case strings.HasPrefix(trimmed, "**Rekomendacja:**"):
			e.Recommendation = strings.TrimSpace(strings.TrimPrefix(trimmed, "**Rekomendacja:**"))
			inReflection = false
		case strings.HasPrefix(trimmed, "**Sygnał błędu:**"):
			e.ErrorSignal = strings.TrimSpace(strings.TrimPrefix(trimmed, "**Sygnał błędu:**"))
			inReflection = false
		case strings.HasPrefix(trimmed, "**Wniosek:**"):
			inReflection = true
		case inReflection && strings.HasPrefix(trimmed, ">"):
			reflection = append(reflection, strings.TrimSpace(strings.TrimPrefix(trimmed, ">")))
		}
	}
	e.Reflection = strings.TrimSpace(strings.Join(reflection, "\n"))
	return e
}
